# 2.1

In [1]:
import numpy as np
from numpy.linalg import eig

In [104]:
# training samples D = {D1,D2}
d1 = [[1,2],[-3,-1],[4,5],[-1,1]]
d2 = [[0,-2],[5,2],[-1,-4],[3,1]]
d = [np.array([i]).transpose() for i in d1+d2]
# mean of training data vector
m = sum(d)/len(d)

In [105]:
# difference between x_k and mean vector
xk_m = [i-m for i in d]

In [106]:
# get dot product of each data sample and its transpose and sum to get S matrix
S_sum = np.sum([i.dot(i.T) for i in xk_m],0)
e_val, e_vec = eig(S_sum)

In [107]:
e_val # eigenvalues lambda = (lambda1, lambda2)

array([91., 17.])

In [108]:
e_vec

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [109]:
# use eigen decomp values to reconstruct data
e = np.amax(e_vec,0) # choose dominant eigenvalue by selecting largest column/eigenvector
# calculate PDA classifier
ak = np.dot(e.T,xk_m)
xk_PCA = m.T + ak*e

In [110]:
xk_PCA

array([[ 1.75,  1.25],
       [-1.75, -2.25],
       [ 4.75,  4.25],
       [ 0.25, -0.25],
       [-0.75, -1.25],
       [ 3.75,  3.25],
       [-2.25, -2.75],
       [ 2.25,  1.75]])

# 2.2

In [111]:
m1,m2 = sum(d[:4])/len(d[:4]), sum(d[4:])/len(d[4:])
m_diff = m1-m2

In [112]:
# difference between x_k and mean vector
xk_m1 = [i-m1 for i in d[:4]]
xk_m2 = [i-m2 for i in d[4:]]

In [113]:
# get dot product of each data sample and its transpose and sum to get S matrix
S1 = np.sum([i.dot(i.T) for i in xk_m1],0)
S2 = np.sum([i.dot(i.T) for i in xk_m2],0)

S = S1 + S2

In [114]:
# calculate LCA classifier
w = np.linalg.inv(S).dot(m_diff)
yk1,yk2 = np.dot(w.T,d[:4]), np.dot(w.T,d[4:])

In [132]:
# reconstruct data
xk_LDA = np.append(yk1.dot(w.T),yk2.dot(w.T),0)

In [133]:
xk_LDA

array([[ -6.57436998,   7.21854456],
       [-10.45562454,  11.48009496],
       [ -8.19023923,   8.99274105],
       [-11.53287071,  12.66289262],
       [ 12.07149379, -13.25429145],
       [ 15.41412527, -16.92444302],
       [ 18.64586377, -20.47283601],
       [ 10.45562454, -11.48009496]])